# Generated by Django 3.0.3 on 2020-05-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('terreno', models.CharField(max_length=20, verbose_name='Terreno')),
                ('area', models.PositiveIntegerField(verbose_name='Area')),
            ],
        ),
    ]
